[script]
name = "wr_official"
version = "0.1.0"
author_ids = ["MotorcycleEnjoyer"]
description = "Adds V Shaped Smoke to Tanks"
repository = "https://github.com/MotorcycleEnjoyer/WR_Mods.git"
tags = ["official", "wr"]

[dependencies]
partitions = "0.1.0"
